name: personal-site-workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature/**, chore/**, bugs/**]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Run Type Checker
        run: npm run check:ts
  build:
    runs-on: ubuntu-latest
    needs: [static-analysis] # require tests latere
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Create Production Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  auto-deploy:
    runs-on: ubuntu-latest
    needs: [build, static-analysis]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          full_commit_message: ${{ github.event.head_commit.message }}
          user_name: "ilopezro"
          user_email: "ilopezro@users.noreply.github.com"
